version: "3.8"

services:
  ai-issue-mgmnt-frontend:
    build: 
      context: frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/frontend
    ports:
      - 3000:3000
    depends_on:
      - ai-issue-mgmnt-backend
  ai-issue-mgmnt-backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080